/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-04-21 01:47:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class NewFile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<title>카카오 지역검색</title>\r\n");
      out.write("\t<script src=\"http://code.jquery.com/jquery-1.9.1.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.1/handlebars.js\"></script>\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\t#tbl{width:800px;border-collapse:collapse;}\r\n");
      out.write("\t\ttd{border:2px solid white;}\r\n");
      out.write("\t\t.row:hover{background:gray; color:white;}\r\n");
      out.write("\t\t.title{background:gray;color:white;}\r\n");
      out.write("\t\t.place{width:200px;text-overflow:ellipsis;white-space:nowrap;overflow:hidden;}\r\n");
      out.write("\t\t.address{width:400px;text-overflow:ellipsis;white-space:nowrap;overflow:hidden;}\r\n");
      out.write("\t\t.phone{width:100px;text-overflow:ellipsis;white-space:nowrap;overflow:hidden;}\r\n");
      out.write("\t\t.location{width:100px;}\r\n");
      out.write("\t\t#map{width:500px;height:400px;border:solid 1px black}\r\n");
      out.write("\t</style>\r\n");
      out.write("\t\r\n");
      out.write("\t<script id=\"temp\" type=\"text/x-handlebars-template\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t<tr class = \"title\">\r\n");
      out.write("\t\t<td>Title</td><td>Address</td><td>Phone</td><td>location</td>\r\n");
      out.write("\t</tr>\t\t\r\n");
      out.write("\r\n");
      out.write("\t{{#each documents}}\r\n");
      out.write("\t\t<tr class = \"row\">\r\n");
      out.write("\t\t\t<td><div class = \"place\">{{place_name}}</div></td>\r\n");
      out.write("\t\t\t<td><div class = \"address\">{{address_name}}</div></td>\r\n");
      out.write("\t\t\t<td><div class = \"phone\">{{phone}}</div></td>\r\n");
      out.write("\t\t\t<td class=\"location\"><button>위치보기</button></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t{{/each}}\r\n");
      out.write("\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=ecfd926a9868e154f7097ff15ab0017a\"></script>\r\n");
      out.write("\t\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h1>[카카오 지역검색]</h1>\r\n");
      out.write("\t<div id=\"search\">\r\n");
      out.write("\t\t검색수:<span id=\"total\"></span>\r\n");
      out.write("\t\t<input type = \"text\" id = \"txtSearch\" value = \"\">\r\n");
      out.write("\t\t<input type = \"button\" id = \"btnSearch\" value = \"검색\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<table id = \"tbl\" ></table>\r\n");
      out.write("\r\n");
      out.write("\t<div id = \"pagination\">\r\n");
      out.write("\t\t<button id = \"btnPre\">이전</button>\r\n");
      out.write("\t\t<span id=\"pageNo\"></span>\r\n");
      out.write("\t\t<button id = \"btnNext\">다음</button>\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 지도 출력 -->\r\n");
      out.write("\t<div id=\"map\"></div>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\tvar is_end;\r\n");
      out.write("\tvar page=1;\r\n");
      out.write("\t\r\n");
      out.write("\tgetList();\r\n");
      out.write("\t\r\n");
      out.write("\tvar container = document.getElementById('map'); //지도를 담을 영역의 DOM 레퍼런스\r\n");
      out.write("\tvar options = { //지도를 생성할 때 필요한 기본 옵션\r\n");
      out.write("\t\tcenter: new kakao.maps.LatLng(33.450701, 126.570667), //지도의 중심좌표.\r\n");
      out.write("\t\tlevel: 3 //지도의 레벨(확대, 축소 정도)\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("\tvar map = new kakao.maps.Map(container, options); //지도 생성 및 객체 리턴\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#btnSearch\").on(\"click\",function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tgetList();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#txtSearch\").keydown(function(key){\r\n");
      out.write("\t\tif(key.keyCode==13){\r\n");
      out.write("\t\t\tgetList();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#btnNext\").on(\"click\", function(){\r\n");
      out.write("      if(is_end==false){\r\n");
      out.write("         page=page+1;\r\n");
      out.write("         getList();\t\r\n");
      out.write("\t }\r\n");
      out.write("\t});\r\n");
      out.write("\t\t   \t\r\n");
      out.write("\t$(\"#btnPre\").on(\"click\", function(){\r\n");
      out.write("      if(page!=1){\r\n");
      out.write("         page=page-1;\r\n");
      out.write("         getList();\t\r\n");
      out.write("      }\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfunction getList(){\r\n");
      out.write("\t\tvar query=$(\"#txtSearch\").val();\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"get\",\r\n");
      out.write("\t\t\turl:\"https://dapi.kakao.com/v2/local/search/keyword.json\",\r\n");
      out.write("\t\t\theaders:{\"Authorization\":\"KakaoAK 550c2430589d8623c802155ee1472416\"},\t\r\n");
      out.write("\t\t\tdataType:\"json\",\r\n");
      out.write("\t\t\tdata:{\"query\":query, \"page\":page, \"size\":10},\r\n");
      out.write("\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\tvar total=data.meta.pageable_count;\r\n");
      out.write("\t\t\t\t$(\"#total\").html(total + \"건\");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tis_end=data.meta.is_end;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar temp = Handlebars.compile($(\"#temp\").html());\r\n");
      out.write("\t\t\t\t$(\"#tbl\").html(temp(data));\t\t\t\r\n");
      out.write("\t\t\t}\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#pageNo\").html(page);\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
