/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-04-17 10:11:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import ex0417.*;
import java.util.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<script src=\"http://code.jquery.com/jquery-1.9.1.js\"></script>\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\t#page{width:650px;background:white;text-align:center;margin:auto;margin-top:50px;padding:25px;box-shadow:10px 10px 3px #43d8c9;}\r\n");
      out.write("\t\th1 {text-align:center;color:#43d8c9}\r\n");
      out.write("\t\tbody{background:#A2F2EA;}\r\n");
      out.write("\t\t.content{margin:10px;text-align:left;width:590px}\r\n");
      out.write("\t\t#content{height:50px;margin:10px;margin-bottom:20px;border:2px solid #43d8c9}\r\n");
      out.write("\t\t.title{text-align:right;margin-right:20px;}\r\n");
      out.write("\t\thr {border:1px dotted #43d8c9;margin-bottom:20px;}\r\n");
      out.write("\t\t.box {border:2px solid #43d8c9;padding:4px;margin-bottom:50px;}\r\n");
      out.write("\t\t.btnDelete{float:right;}\r\n");
      out.write("\t\t.date{float:left;margin-left:10px;font-size:11px;}\r\n");
      out.write("\t\t.like{margin-right:15px}\r\n");
      out.write("\t</style>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<title>fk</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"page\">\r\n");
      out.write("\t<h1>[댓글관리]</h1>\t\r\n");
      out.write("\t\t<input type=\"text\" id=\"content\" size=50px>\r\n");
      out.write("\t\t<input type=\"button\" value=\"저장\" id=\"btnInsert\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");

			ReplyDAO dao=new ReplyDAO();
			ArrayList<ReplyVO> list= dao.list();
			out.println("<div class='box'>");
			for(int i=0;i<list.size();i++){
				ReplyVO vo = list.get(i);
				int rno=vo.getRno();
				String content=vo.getContent();
				Date wdate=vo.getWdate();
				int cnt=vo.getCnt();
				out.println("<div class='rno'rno=" + rno +">");
				out.println("<div class='content'>");
				out.println(content+"<input type='button' value='X' class='btnDelete'></div>");
				out.println("<div class='title'>");
				out.println("<span class='date'>"+wdate+"</span>");
				out.println("<span>"+cnt+"</span>");
				out.println("<input type='button' class='like' value='♬'>");			
				out.println("<hr size=1px>");
				out.println("</div>");	
				out.println("</div>");	
			}
			out.println("</div>");
		
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(\"#btnInsert\").on(\"click\", function(){\r\n");
      out.write("\t\tif(confirm(\"댓글 달아요?\")==false) return;\r\n");
      out.write("\t\tvar content=$(\"#content\").val();\r\n");
      out.write("\t\tlocation.href=\"sqlInsert.jsp?content=\"+content;\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".btnDelete\").on(\"click\", function(){\r\n");
      out.write("\t\tvar rno=$(this).parent().parent().attr(\"rno\");\r\n");
      out.write("\t\tif(confirm(\"삭제해요?\")==false) return;\t\r\n");
      out.write("\t\tlocation.href=\"sqlDelete.jsp?rno=\"+rno;\r\n");
      out.write("\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t$(\".like\").on(\"click\", function(){\r\n");
      out.write("\t\tvar rno=$(this).parent().parent().attr(\"rno\");\r\n");
      out.write("\t\tif(confirm(\"좋아요를 누르시겠습니까?\")==false)return;\r\n");
      out.write("\t\tlocation.href=\"sqlUpdate.jsp?rno=\"+rno;\r\n");
      out.write("\t});\r\n");
      out.write("\t\t\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
