/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-05-07 01:46:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import ex0507.*;
import java.text.*;
import java.util.*;

public final class plist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<title>교수입력</title>\r\n");
      out.write("\t<script src=\"http://code.jquery.com/jquery-1.9.1.js\"></script>\r\n");
      out.write(" \t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.1/handlebars.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h1>교수입력</h1>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t교수번호 : <input type = \"text\" id= \"txtpcode\" maxlength=3>\r\n");
      out.write("\t\t교수명 : <input type = \"text\" id= \"txtpname\">\r\n");
      out.write("\t\t<input type = \"button\" id = \"btnSave\" value=\"저장\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<table>\r\n");
      out.write("\t<tr class = stitle>\r\n");
      out.write("\t\t\t<td></td>\r\n");
      out.write("\t\t\t<td>학생명</td>\r\n");
      out.write("\t\t\t<td>학과</td>\r\n");
      out.write("\t\t\t<td>지도교수명</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");

		DAO pdao = new DAO();
		ArrayList<PVO> list = pdao.list();
		for(PVO vo:list){
			out.println("<tr class = srow>");
			out.println("<td class = scode>"+vo.getPcode() + "</td>");
			out.println("<td>"+vo.getPname() + "</td>");
			out.println("<td>"+vo.getDept() + "</td>");
			out.println("<td>"+vo.getHireDate() + "</td>");
			out.println("<td>"+vo.getTitle() + "</td>");
			out.println("<td>"+vo.getSalary() + "</td>");
			out.println("</tr>");
		}
		
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(\"#btnSave\").on(\"click\", function(){\r\n");
      out.write("\t\tif(!confirm(\"저장하시겠습니까?\")) return;\r\n");
      out.write("\t\tvar pcode=$(\"#txtpcode\").val();\r\n");
      out.write("\t\tvar pname=$(\"#txtpname\").val();\r\n");
      out.write("\t\tif(pcode.lenth==0 || pcode.length!=3){\r\n");
      out.write("\t\t\talert(\"교수번호를 다시 입력하세요\")\r\n");
      out.write("\t\t\t$(\"txtpcode\").focus();\r\n");
      out.write("\t\t}else if(pname.length == 0 ){\r\n");
      out.write("\t\t\talert(\"교수명을 입력하세요!\");\r\n");
      out.write("\t\t\t$(\"txtpname\").focus();\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t//저장\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\t\turl:\"pinsert.jsp\",\r\n");
      out.write("\t\t\t\tdata:{\"pcode\":pcode, \"pname\":pname},\r\n");
      out.write("\t\t\t\tsuccess:function(){\r\n");
      out.write("\t\t\t\t\talert(\"저장완료\")\r\n");
      out.write("\t\t\t\t\t$(\"#txtpcode\").val(\"\");\r\n");
      out.write("\t\t\t\t\t$(\"#txtpname\").val(\"\");\r\n");
      out.write("\t\t\t\t\t$(\"#txtpcode\").focus();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
